### ISSUE TITLE
Can no longer build on macOS

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#362]
macOS anaconda builds seem to have been broken at some point after scikit build 0.6 or so, or maybe on upgrading to macOS 10.13, I'm not sure which. I now get the error:

```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
      ld: library not found for -lstdc++
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe [as of here](https://scikit-build.readthedocs.io/en/latest/generators.html#default-deployment-target-and-architecture) this is now forced to be 10.6 which breaks the compiler.

Edit: Broken on homebrew Python too.

Edit 2: This works correctly on Scikit-build 0.6.1 on the current macOS.

**Comment by jcfr** [comment]
Look like we need to have a different default for Python 3.x, I think we could initialize to `10.9` in that case.

**Comment by jcfr** [comment]
See also https://github.com/conda-forge/scikit-build-feedstock/pull/18

**Comment by henryiii** [comment]
Python 2 has the same problem - the issue is that macOS 10.14 has removed libstdc++ in favor of libc++, so nothing containing C++ can build if set to <10.9. It looks like there is both an option and a variable to change the target, are those supported in Scikit-build? <https://packaging.python.org/guides/packaging-binary-extensions/#binary-extensions-for-macos>

**Comment by jakirkham** [comment]
@henryiii, the new compilers, which we are rebuilding with, ship their own libcxx. So we won’t be relying on the system copy for much longer.

**Comment by hameerabbasi** [comment]
I can no longer build on v0.8.1 with `MACOSX_DEPLOYMENT_TARGET="10.9" pip install -e .` either, or explicitly setting it inside the config.

**Comment by jcfr** [comment]
Thanks for the report.

Would you have more details about the error ?

Did it start to fail with 0.8.1 or did you update to 0.8.1 ?

**Comment by hameerabbasi** [comment]
I can try out older versions, but I tried it just now and it fails. If I run `cmake .` it goes past this but stops at finding `FindPythonExtensions.cmake`, so it's definitely a scikit-build issue. Here's the log:


```
CMake Error at /Users/hameerabbasi/anaconda/envs/mtypes/share/cmake-3.12/Modules/CMakeTestCXXCompiler.cmake:45 (message):
      The C++ compiler
    
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"
    
      is not able to compile a simple test program.
    
      It fails with the following output:
    
        Change Dir: /Users/hameerabbasi/Quansight/mtypes/_cmake_test_compile/build/CMakeFiles/CMakeTmp
    
        Run Build Command:"/Users/hameerabbasi/anaconda/envs/mtypes/bin/ninja" "cmTC_10586"
        [1/2] Building CXX object CMakeFiles/cmTC_10586.dir/testCXXCompiler.cxx.o
        warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
        1 warning generated.
        [2/2] Linking CXX executable cmTC_10586
        FAILED: cmTC_10586
        : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_10586.dir/testCXXCompiler.cxx.o  -o cmTC_10586   && :
        clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
        ld: library not found for -lstdc++
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.
    
    
    
    
      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:4 (ENABLE_LANGUAGE)
```

**Comment by hameerabbasi** [comment]
I just tried it now and it failed, I cannot use `0.8.0` because I need Python 3.7 support.

**Comment by hameerabbasi** [comment]
Does [this](https://scikit-build.readthedocs.io/en/latest/generators.html?highlight=10.6#default-deployment-target-and-architecture) have something to do with it, or [this](https://github.com/scikit-build/scikit-build/blob/052aa666dea4d78496ee1fb9dbce3d4bf7dd6f6f/skbuild/setuptools_wrap.py#L484)? Or [this](https://github.com/scikit-build/scikit-build/blob/3c6bcf01704c74652198d4ced748d4801e71120b/skbuild/command/bdist_wheel.py#L69)?

Hardcoding anything is bad, in general. 🙂

**Comment by jcfr** [comment]
I think this is most likely already fixed in the the development version of scikit-build. See https://scikit-build.readthedocs.io/en/latest/changes.html#bug-fixes

A release is on the way

**Comment by jcfr** [comment]
scikit-build 0.9.0 has just been release. See https://pypi.org/project/scikit-build/#history

**Comment by hameerabbasi** [comment]
Could you release on conda please? ;)

**Comment by hameerabbasi** [comment]
I just installed from `pip` and the issue is still there:

```
Building CXX object CMakeFiles/cmTC_0fda5.dir/testCXXCompiler.cxx.o
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6   -o CMakeFiles/cmTC_0fda5.dir/testCXXCompiler.cxx.o -c /Users/hameerabbasi/Quansight/mtypes/_cmake_test_compile/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
```

Output from: `MACOSX_DEPLOYMENT_TARGET="10.9" pip install -e .`

**Comment by jcfr** [comment]
> Could you release on conda please? ;)

This is in progress: https://github.com/conda-forge/scikit-build-feedstock/pull/22 and https://github.com/conda-forge/scikit-build-feedstock/pull/21

There are few issues that are being addressed.

> Output from: `MACOSX_DEPLOYMENT_TARGET="10.9" pip install -e .`

Settings the environment variable `MACOSX_DEPLOYMENT_TARGET` doesn't seems to be supported by pip. See https://pip.pypa.io/en/stable/reference/pip_install/

To explicitly set the deployment target, I suggest to use approaches documented in https://scikit-build.readthedocs.io/en/latest/generators.html#customizing-deployment-target-and-architecture


To allow using pip directly, you could look at the options `--global-option` and `--install-option` documented in https://pip.pypa.io/en/stable/reference/pip_install/#per-requirement-overrides and investigate how scikit-build could be improved to make sure of them. It is currently not tested.

**Comment by henryiii** [comment]
I will check further, but 0.9.0 still seems to be broken on macOS with a c++11 library, even on 10.12. Requiring 10.6 gives libstdc++, which is wrong. Forcing 0.6.1 fixes the issue still.

**Comment by jcfr** [comment]
@henryiii  

if you explicitly set the deployment target using any of the approach documented in https://scikit-build.readthedocs.io/en/latest/generators.html#customizing-deployment-target-and-architecture, is the compilation successful ? 

If yes, changing the default deployment target from 10.6 to 10.9 should address this.

**Comment by isuruf** [comment]
I and @certik tried different ways of using `install_option` and `global_option` for `pip` to customize as in https://scikit-build.readthedocs.io/en/latest/generators.html#customizing-deployment-target-and-architecture, but none worked. Changing the setup.py and adding to `cmake_args` was the only way and I wished there was a way to install with pip without changing the source.

**Comment by isuruf** [comment]
Also, on projects with a pyproject.toml, setting `install_option` means dependencies are also built with that option and therefore deps like `cmake` is also installed from source, which takes a long time.

**Comment by certik** [comment]
Here is how to modify `setup.py` to do the right thing: https://gitlab.com/lfortran/lfortran/merge_requests/229

**Comment by jcfr** [comment]
> Here is how to modify setup.py to do the right thing: https://gitlab.com/lfortran/lfortran/merge_requests/229

That approach makes sense. As a convenience, we could also update scikit-build to understand the `MACOSX_DEPLOYMENT_TARGET` env. variable. I would be happy to review PR implementing this.

Following code should be updated: https://github.com/scikit-build/scikit-build/blob/54378a86b3ab6020bc88a1225188d3b5716217a1/skbuild/constants.py#L15-L30

**Comment by jcfr** [comment]
> to review PR implementing this

Thanks @certik 

For reference, see #441

**Comment by certik** [comment]
@jcfr should I make #441 to fix this issue #362?

**Comment by mbargull** [comment]
https://github.com/conda-forge/scikit-build-feedstock/pull/25 builds a patched `0.10.0` that includes two Py3.8-related fixes and also @certik's changes from gh-441, if someone wants to give that a spin.

**Comment by henryiii** [comment]
scikit-build is now the largest package holding up the Python 3.8 migration on Conda-forge. A new release would be very helpful!

**Comment by jcfr** [comment]
@mbargull  @henryiii  Thanks for the summary and the ping.

In the interest of time, and waiting for [scikit-build 0.11](https://github.com/scikit-build/scikit-build/milestone/4), I don't see any problem with moving forward with the plan described in https://github.com/conda-forge/scikit-build-feedstock/pull/25#issuecomment-574762811

Note that I just created a milestone with the issues that should be addressed before we release 0.11

Questions:
* Is there any other issues we should consider addressing in release 0.11 ? 
* @henryiii  Could you confirm that we can close this issue ?

**Comment by henryiii** [comment]
Looks like the current version works on macOS. Thanks!

**Comment by henryiii** [comment]
Any chance to get a 0.11 release out? The lack of support for Python 3.8 on pip is killing my conversion of a package from an external call to CMake to Scikit-build.
